# Generated by Django 4.2.20 on 2025-04-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
